variables:
  MIRROR_REPO: git@github.com:thm-projects/arsnova-admininterface.git
  WAR_FILE: dist/arsnova-admininterface.war

stages:
  - test
  - build
  - deploy
  - synchronization

cache:
  paths:
    - node_modules/
    
jshint:
  stage: test
  tags:
    - nodejs
  dependencies: []
  script:
    - npm install jshint@^2.9.0
    - node_modules/jshint/bin/jshint --config .jshintrc ./js

jscs:
  stage: test
  tags:
    - nodejs
  dependencies: []
  script:
    - npm install jscs
    - node_modules/jscs/bin/jscs --config .jscsrc ./js


sync_mirror:
  stage: synchronization
  when: always
  except:
    - master
    - staging
  allow_failure: true
  script:
    - git clone --bare "$CI_BUILD_REPO" mirror.git
    - cd mirror.git
    - git update-ref -d refs/tags/production
    - git update-ref -d refs/tags/staging
    - git push --mirror "$MIRROR_REPO"

package:
  stage: build
  tags:
    - nodejs
  artifacts:
    paths:
      - $WAR_FILE
  script:
    - npm install -g gulp
    - npm install
    - gulp war

tomcat_production:
  stage: deploy
  only:
    - master
  script:
    - curl --fail --upload-file "$WAR_FILE" "https://$PROD_TOMCAT_USER:$PROD_TOMCAT_PASSWORD@$PROD_TOMCAT_HOST/manager/text/deploy?path=%2Fadmin&update=true"

tomcat_development:
  stage: deploy
  only:
    - staging
  script:
    - curl --fail --upload-file $WAR_FILE "https://$DEV_TOMCAT_USER:$DEV_TOMCAT_PASSWORD@$DEV_TOMCAT_HOST/manager/text/deploy?path=%2Fadmin&update=true"