App.Model.SkillQuestion = Backbone.Model.extend({
	defaults: {
		_rev: "",
		abstention: "",
		active: "",
		duration: "",
		noCorrect: "",
		type: "",
		number: "",
		piRound: "",
		piRoundActive: "",
		piRoundStartTime: "",
		piRoundEndTime: "",
		piRoundFinished: "",
		votingDisabled: "",
		possibleAnswers: "",
		questionType: "",
		questionVariant: "",
		releasedFor: "",
		session: "",
		sessionId: "",
		sessionKeyword: "",
		showAnswer: "",
		showStatistic: "",
		subject: "",
		text: "",
		timestamp: "",
		gridSize: "",
		offsetX: "",
		offsetY: "",
		zoomLvl: "",
		image: "",
		fcImage: "",
		gridOffsetX: "",
		gridOffsetY: "",
		gridZoomLvl: "",
		gridSizeX: "",
		gridSizeY: "",
		gridIsHidden: "",
		imgRotation: "",
		toggleFieldsLeft: "",
		numClickableFields: "",
		thresholdCorrectAnswers: "",
		cvIsColored: "",
		gridLineColor: "",
		numberOfDots: "",
		gridType: "",
		scaleFactor: "",
		gridScaleFactor: "",
		imageQuestion: "",
		textAnswerEnabled: "",
		hint: "",
		solution: "",
	},
	initialize: function () {
	},
});
